In [5]:

import jax.numpy as jnp

import sys
sys.path.insert(1,'../scripts/')

import utils
import loader_modif
import tqdm
%load_ext autoreload
%autoreload 2
import imp
imp.reload(loader_modif)
import setup
import scipy.stats as sts
from matplotlib import pyplot as plt

import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
import pandas as pd


pd.read_parquet('../data2/2022_Q2_IBL_et_al_RepeatedSite/datasets.pqt')

                                                                                                                    rel_path  \
eid                                  id
e2b845a1-e313-4a08-bc61-a5f662ed295e 012bf9d0-765c-4743-81da-4f8db39c9a19           alf/probe01/pykilosort/clusters.amps.npy
                                     017096ae-7bd2-460a-88b6-140697ff7d9c  alf/probe00/pykilosort/#2024-03-22#/channels.l...
                                     02af0527-b889-4977-bba4-3a733977b4e7                 alf/_ibl_trials.intervals_bpod.npy
                                     04082c19-c1da-4b3b-ad2b-32f850423033  alf/probe01/pykilosort/#2024-05-06#/channels.m...
                                     05f3f3f8-22e1-4f75-9115-16e0cc741083  alf/probe00/pykilosort/#2024-05-06#/waveforms....
...                                                                                                                      ...
                                     f9b6bbe8-a542-4c16-ae7b-0fc8969332cc  alf/probe00/pykilosort/#2024-05-06#/waveforms....
                                     fbbf52fe-fbc1-43b4-8715-099a134cd67d        alf/probe01/pykilosort/spikes.templates.npy
                                     fbc7a25e-30eb-4dad-b311-117032c0f71b  alf/probe01/pykilosort/#2024-05-06#/clusters.u...
                                     fdd0550a-ec1e-4172-b54f-043e76e0396b  alf/probe01/pykilosort/clusters.waveformsChann...
                                     ff3df3bc-be72-4530-b3da-9ebdf4f23e9f  raw_ephys_data/probe01/_spikeglx_ephysData_g0_...

                                                                            file_size  \
eid                                  id
e2b845a1-e313-4a08-bc61-a5f662ed295e 012bf9d0-765c-4743-81da-4f8db39c9a19        6496
                                     017096ae-7bd2-460a-88b6-140697ff7d9c        3200
                                     02af0527-b889-4977-bba4-3a733977b4e7        7744
                                     04082c19-c1da-4b3b-ad2b-32f850423033        4736
                                     05f3f3f8-22e1-4f75-9115-16e0cc741083     5236382
...                                                                               ...
                                     f9b6bbe8-a542-4c16-ae7b-0fc8969332cc  2859991168
                                     fbbf52fe-fbc1-43b4-8715-099a134cd67d    54080064
                                     fbc7a25e-30eb-4dad-b311-117032c0f71b       58835
                                     fdd0550a-ec1e-4172-b54f-043e76e0396b      102016
                                     ff3df3bc-be72-4530-b3da-9ebdf4f23e9f      181478

                                                                                                       hash  \
eid                                  id
e2b845a1-e313-4a08-bc61-a5f662ed295e 012bf9d0-765c-4743-81da-4f8db39c9a19  802a4e9dbdac48d154d4d6232b2e6a46
                                     017096ae-7bd2-460a-88b6-140697ff7d9c  e7488812d80f6f7bb4f19fd946fd77d3
                                     02af0527-b889-4977-bba4-3a733977b4e7  203ef50cdb804c7dc9632e370f71e10b
                                     04082c19-c1da-4b3b-ad2b-32f850423033  92964ed7a67fb0320abef48019655072
                                     05f3f3f8-22e1-4f75-9115-16e0cc741083  dcb395f52e4d62732cd6b5aa137b0a47
...                                                                                                     ...
                                     f9b6bbe8-a542-4c16-ae7b-0fc8969332cc  5191a706605d4906531e904ef9b6836d
                                     fbbf52fe-fbc1-43b4-8715-099a134cd67d  791bd266fe4e935448eb16538360b6fe
                                     fbc7a25e-30eb-4dad-b311-117032c0f71b  1e86d0adc7620ca8e2101ff7490cc96d
                                     fdd0550a-ec1e-4172-b54f-043e76e0396b  2a8ba333a28e72d976aa8599238af55c
                                     ff3df3bc-be72-4530-b3da-9ebdf4f23e9f  92c3000fd47f1bb1f5242c3b9ade04fd

                                                                           exists  \
eid                                  id
e2b845a1-e313-4a08-bc61-a5f662ed295e 012bf9d0-765c-4743-81da-4f8db39c9a19    True
                                     017096ae-7bd2-460a-88b6-140697ff7d9c    True
                                     02af0527-b889-4977-bba4-3a733977b4e7    True
                                     04082c19-c1da-4b3b-ad2b-32f850423033    True
                                     05f3f3f8-22e1-4f75-9115-16e0cc741083    True
...                                                                           ...
                                     f9b6bbe8-a542-4c16-ae7b-0fc8969332cc    True
                                     fbbf52fe-fbc1-43b4-8715-099a134cd67d    True
                                     fbc7a25e-30eb-4dad-b311-117032c0f71b    True
                                     fdd0550a-ec1e-4172-b54f-043e76e0396b    True
                                     ff3df3bc-be72-4530-b3da-9ebdf4f23e9f    True

                                                                                qc
eid                                  id
e2b845a1-e313-4a08-bc61-a5f662ed295e 012bf9d0-765c-4743-81da-4f8db39c9a19  NOT_SET
                                     017096ae-7bd2-460a-88b6-140697ff7d9c  NOT_SET
                                     02af0527-b889-4977-bba4-3a733977b4e7  NOT_SET
                                     04082c19-c1da-4b3b-ad2b-32f850423033  NOT_SET
                                     05f3f3f8-22e1-4f75-9115-16e0cc741083  NOT_SET
...                                                                            ...
                                     f9b6bbe8-a542-4c16-ae7b-0fc8969332cc  NOT_SET
                                     fbbf52fe-fbc1-43b4-8715-099a134cd67d  NOT_SET
                                     fbc7a25e-30eb-4dad-b311-117032c0f71b  NOT_SET
                                     fdd0550a-ec1e-4172-b54f-043e76e0396b  NOT_SET
                                     ff3df3bc-be72-4530-b3da-9ebdf4f23e9f  NOT_SET

[252 rows x 5 columns]

In [13]:
## For debugging: load IBL data
from pathlib import Path
import numpy as np
import pandas as pd

possible_dir = ["","_new"]

differences = {}

for p in possible_dir:

    cache_dir = Path(f"../data{p}/2022_Q2_IBL_et_al_RepeatedSite")

    # Find all ALF directories
    alf_dirs = list(cache_dir.rglob("alf"))
    print(f"Found {len(alf_dirs)} sessions with ALF data")
    n_trials = {}

    for i, alf in enumerate(alf_dirs):
        try:
            stimOff = np.load(alf / "_ibl_trials.stimOff_times.npy")
            n_trials[alf.parent.parent.parent.name] = len(stimOff)
            goCue = np.load(alf / "_ibl_trials.goCueTrigger_times.npy")
            trials_table = pd.read_parquet(alf / "_ibl_trials.table.pqt")
            print(f"Session: {i}, Trials: {len(stimOff)}")
        except:
            continue

    n_trials = pd.Series(n_trials)

    differences[f'data{p}'] = n_trials

Found 36 sessions with ALF data
Session: 0, Trials: 472
Session: 1, Trials: 550
Session: 2, Trials: 414
Session: 3, Trials: 1028
Session: 4, Trials: 505
Session: 5, Trials: 1132
Session: 6, Trials: 891
Session: 7, Trials: 828
Session: 8, Trials: 587
Session: 9, Trials: 478
Session: 10, Trials: 490
Session: 11, Trials: 780
Session: 12, Trials: 733
Session: 13, Trials: 560
Session: 14, Trials: 424
Session: 15, Trials: 660
Session: 16, Trials: 452
Session: 17, Trials: 848
Session: 18, Trials: 994
Session: 19, Trials: 625
Session: 20, Trials: 663
Session: 21, Trials: 751
Session: 22, Trials: 510
Session: 23, Trials: 626
Session: 24, Trials: 842
Session: 25, Trials: 623
Session: 26, Trials: 401
Session: 27, Trials: 410
Session: 28, Trials: 402
Session: 29, Trials: 402
Session: 30, Trials: 476
Session: 31, Trials: 580
Session: 32, Trials: 724
Session: 33, Trials: 764
Session: 34, Trials: 894
Session: 35, Trials: 1013
Found 33 sessions with ALF data
Session: 0, Trials: 472
Session: 1, Trials: 550
Session: 3, Trials: 1028
Session: 5, Trials: 891
Session: 6, Trials: 828
Session: 7, Trials: 587
Session: 9, Trials: 780
Session: 11, Trials: 560
Session: 14, Trials: 452
Session: 15, Trials: 848
Session: 16, Trials: 994
Session: 17, Trials: 625
Session: 18, Trials: 663
Session: 19, Trials: 751
Session: 20, Trials: 510
Session: 21, Trials: 626
Session: 22, Trials: 842
Session: 25, Trials: 410
Session: 26, Trials: 402
Session: 27, Trials: 402
Session: 28, Trials: 476
Session: 30, Trials: 764
Session: 32, Trials: 1013

In [48]:
pd.DataFrame(differences)

                 data   data2
CSHL049         842.0   842.0
CSHL051         510.0   510.0
CSHL058         626.0   626.0
CSHL059         751.0   751.0
CSH_ZAD_001       NaN   310.0
CSH_ZAD_019    1013.0  1013.0
CSH_ZAD_026     894.0   894.0
DY_009          402.0   402.0
DY_010          402.0   402.0
DY_016          410.0   410.0
DY_018          623.0   623.0
DY_020          401.0   401.0
KS051           478.0   478.0
KS074           587.0   587.0
KS075           828.0   828.0
KS094           490.0     NaN
NYU-12          550.0   550.0
NYU-21          891.0   891.0
NYU-26         1132.0  1132.0
NYU-29         1028.0  1028.0
NYU-37          414.0   414.0
NYU-45          505.0   505.0
NYU-48          472.0   472.0
UCLA011         764.0   764.0
UCLA033         724.0   724.0
UCLA036         476.0   476.0
UCLA037         580.0   580.0
ZFM-01576       848.0   848.0
ZFM-01592       660.0   660.0
ZFM-01936       560.0   560.0
ZFM-02369       733.0   733.0
ZFM-02372       452.0   452.0
ZFM-02373       424.0   424.0
ZM_2241         994.0   994.0
ZM_3001         780.0   780.0
ibl_witten_27   625.0   625.0
ibl_witten_29   663.0   663.0

In [12]:
## For debugging: load IBL data
from pathlib import Path
import numpy as np
import pandas as pd

cache_dir = Path("../data/2022_Q2_IBL_et_al_RepeatedSite")

#datasets = pd.read_parquet(cache_dir / "datasets.pqt")
#sessions = pd.read_parquet(cache_dir / "sessions.pqt")

# Find all ALF directories
alf_dirs = list(cache_dir.rglob("alf"))
print(f"Found {len(alf_dirs)} sessions with ALF data")

# Load from first session
alf = alf_dirs[-1]
stimOff = np.load(alf / "_ibl_trials.stimOff_times.npy")
goCue = np.load(alf / "_ibl_trials.goCueTrigger_times.npy")
trials_table = pd.read_parquet(alf / "_ibl_trials.table.pqt")

print(f"Loaded {len(stimOff)} trials")
print(f"Trials table columns: {trials_table.columns.tolist()}")

Found 36 sessions with ALF data
Loaded 1013 trials
Trials table columns: ['choice', 'contrastRight', 'probabilityLeft', 'intervals_0', 'intervals_1', 'firstMovement_times', 'feedback_times', 'feedbackType', 'goCue_times', 'response_times', 'contrastLeft', 'stimOn_times', 'rewardVolume']

In [ ]:

params = {
    'file': '../data/', #'../../../Data/',
    'tag': '2022_Q2_IBL_et_al_RepeatedSite',
    'probe': 'probe00',
    'sessions': [0, 5, 6],
    # 'sessions': [5,6,7,8,9,10,11,12],
    'areas': ['CA1','DG','LP','PO','VISa'],
    'props':{'train':.5,'test':.5,'validation':0},
    'seeds':{'train':0,'test':1,'validation':2},
    'n_neurons': None, # all neurons
    'n_trials': None, # all trials
    'pre_time':1,
    'post_time':1,
    'n_bins': 150,
    'align_to': 'stim',
    'train_trial_prop':.9, 
    'train_condition_prop':1, 
    'seed':0,
    'verbose': False,
    'bins_as_conds': False
}

dataloader = loader.IBLDataLoader(
    params,eids=setup.good_eids,parallel=False
)

In [8]:
xs,ys,rs,cs = dataloader.load_train_data()
ys = np.array(ys)

/var/folders/6w/snfd5vc50jb775fq8364m1d80000gn/T/ipykernel_32498/4188501355.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ys = np.array(ys)

In [ ]:
"""# save data 
with(open("25_avg_folds_stim_aligned.pkl","wb")) as f:
    import pickle
    pickle.dump([params,_ys,train_data_folds,test_data_folds],f)
"""

In [ ]:
{'file': '../data/',
 'tag': '2022_Q2_IBL_et_al_RepeatedSite',
 'probe': 'probe00',
 'sessions': [0, 5, 6],
 'areas': ['CA1', 'DG', 'LP', 'PO', 'VISa'],
 'props': {'train': 0.5, 'test': 0.5, 'validation': 0},
 'seeds': {'train': 0, 'test': 1, 'validation': 2},
 'n_neurons': None,
 'n_trials': None,
 'pre_time': 0,
 'post_time': 0.4,
 'n_bins': 10,
 'align_to': 'response',
 'train_trial_prop': 0.9,
 'train_condition_prop': 1,
 'seed': 0,
 'verbose': False,
 'bins_as_conds': True}

In [6]:
params = {
    'file': '../data_new/', #'../../../Data/',
    'tag': '2022_Q2_IBL_et_al_RepeatedSite',
    'probe': 'probe00',
    'sessions': [0,5,6],
    'areas': ['CA1','DG','LP','PO','VISa'],
    'props':{'train':.5,'test':.5,'validation':0},
    'seeds':{'train':0,'test':1,'validation':2},
    'n_neurons': None, # all neurons
    'n_trials': None, # all trials
    'pre_time':0,
    'post_time':0.4,
    'n_bins': 10,
    'align_to': 'response',
    'train_trial_prop':.9, 
    'train_condition_prop':1, 
    'seed':0,
    'verbose': False,
    'bins_as_conds': True,
    'mode':'local' ## Local or remote. Remote if testing
    }

dataloader = loader_modif.IBLDataLoader(
         params,eids=setup.good_eids
)

Connected to https://openalyx.internationalbrainlab.org as user "intbrainlab"
Connected to https://openalyx.internationalbrainlab.org as user "intbrainlab"
Loading spike sorting for session  e2b845a1-e313-4a08-bc61-a5f662ed295e
Len clusters:  27
Loading spike sorting for session  2bdf206a-820f-402f-920a-9e86cd5388a4
Len clusters:  27
Loading spike sorting for session  5dcee0eb-b34d-4652-acc3-d10afc6eae68
Len clusters:  27
Loading spike sorting for session  c7bf2d49-4937-4597-b307-9f39cb1c7b16
Len clusters:  27
Loading spike sorting for session  824cf03d-4012-4ab1-b499-c83a92c5589e
Len clusters:  27
Loading spike sorting for session  51e53aff-1d5d-4182-a684-aba783d50ae5
Len clusters:  27
Loading spike sorting for session  c51f34d8-42f6-4c9c-bb5b-669fd9c42cd9
Len clusters:  27
Loading spike sorting for session  0802ced5-33a3-405e-8336-b65ebc5cb07c
Len clusters:  27
Loading spike sorting for session  d2832a38-27f6-452d-91d6-af72d794136c
Len clusters:  27
Loading spike sorting for session  88224abb-5746-431f-9c17-17d7ef806e6a
Len clusters:  27
Loading spike sorting for session  72cb5550-43b4-4ef0-add5-e4adfdfb5e02
Len clusters:  27
Loading spike sorting for session  0a018f12-ee06-4b11-97aa-bbbff5448e9f
Len clusters:  27
Loading spike sorting for session  7af49c00-63dd-4fed-b2e0-1b3bd945b20b
Len clusters:  27
Loading spike sorting for session  73918ae1-e4fd-4c18-b132-00cb555b1ad2
Len clusters:  27
Loading spike sorting for session  d0ea3148-948d-4817-94f8-dcaf2342bbbe
Len clusters:  27
Loading spike sorting for session  c4432264-e1ae-446f-8a07-6280abade813
Len clusters:  27
Loading spike sorting for session  746d1902-fa59-4cab-b0aa-013be36060d5
Len clusters:  27
Loading spike sorting for session  54238fd6-d2d0-4408-b1a9-d19d24fd29ce
Len clusters:  27
Loading spike sorting for session  4a45c8ba-db6f-4f11-9403-56e06a33dfa4
Len clusters:  27
Loading spike sorting for session  754b74d5-7a06-4004-ae0c-72a10b6ed2e6
Len clusters:  27
Loading spike sorting for session  d23a44ef-1402-4ed7-97f5-47e9a7a504d9
Len clusters:  27
Loading spike sorting for session  15763234-d21e-491f-a01b-1238eb96d389
Len clusters:  27
Loading spike sorting for session  7f6b86f9-879a-4ea2-8531-294a221af5d0
Len clusters:  27
Loading spike sorting for session  61e11a11-ab65-48fb-ae08-3cb80662e5d6
Len clusters:  27
Loading spike sorting for session  c7248e09-8c0d-40f2-9eb4-700a8973d8c8
Len clusters:  27
Loading spike sorting for session  f312aaec-3b6f-44b3-86b4-3a0c119c0438
Len clusters:  27
Loading spike sorting for session  dda5fc59-f09a-4256-9fb5-66c67667a466
Len clusters:  27
Loading spike sorting for session  db4df448-e449-4a6f-a0e7-288711e7a75a
Len clusters:  27
Loading spike sorting for session  ecb5520d-1358-434c-95ec-93687ecd1396
Len clusters:  27
Loading spike sorting for session  ee40aece-cffd-4edb-a4b6-155f158c666a
Len clusters:  27
Loading spike sorting for session  b03fbc44-3d8e-4a6c-8a50-5ea3498568e0
Len clusters:  27
Loading spike sorting for session  a8a8af78-16de-4841-ab07-fde4b5281a03
Len clusters:  27
Loading spike sorting for session  4b7fbad4-f6de-43b4-9b15-c7c7ef44db4b
Len clusters:  27
Loading spike sorting for session  e2b845a1-e313-4a08-bc61-a5f662ed295e
Loading spike sorting for session  2bdf206a-820f-402f-920a-9e86cd5388a4
Loading spike sorting for session  5dcee0eb-b34d-4652-acc3-d10afc6eae68
Loading spike sorting for session  c7bf2d49-4937-4597-b307-9f39cb1c7b16
Loading spike sorting for session  824cf03d-4012-4ab1-b499-c83a92c5589e
Loading spike sorting for session  51e53aff-1d5d-4182-a684-aba783d50ae5
Loading spike sorting for session  c51f34d8-42f6-4c9c-bb5b-669fd9c42cd9
Loading spike sorting for session  0802ced5-33a3-405e-8336-b65ebc5cb07c
Loading spike sorting for session  d2832a38-27f6-452d-91d6-af72d794136c
Loading spike sorting for session  88224abb-5746-431f-9c17-17d7ef806e6a
Loading spike sorting for session  72cb5550-43b4-4ef0-add5-e4adfdfb5e02
Loading spike sorting for session  0a018f12-ee06-4b11-97aa-bbbff5448e9f
Loading spike sorting for session  7af49c00-63dd-4fed-b2e0-1b3bd945b20b
Loading spike sorting for session  73918ae1-e4fd-4c18-b132-00cb555b1ad2
Loading spike sorting for session  d0ea3148-948d-4817-94f8-dcaf2342bbbe
Loading spike sorting for session  c4432264-e1ae-446f-8a07-6280abade813
Loading spike sorting for session  746d1902-fa59-4cab-b0aa-013be36060d5
Loading spike sorting for session  54238fd6-d2d0-4408-b1a9-d19d24fd29ce
Loading spike sorting for session  4a45c8ba-db6f-4f11-9403-56e06a33dfa4
Loading spike sorting for session  754b74d5-7a06-4004-ae0c-72a10b6ed2e6
Loading spike sorting for session  d23a44ef-1402-4ed7-97f5-47e9a7a504d9
Loading spike sorting for session  15763234-d21e-491f-a01b-1238eb96d389
Loading spike sorting for session  7f6b86f9-879a-4ea2-8531-294a221af5d0
Loading spike sorting for session  61e11a11-ab65-48fb-ae08-3cb80662e5d6
Loading spike sorting for session  c7248e09-8c0d-40f2-9eb4-700a8973d8c8
Loading spike sorting for session  f312aaec-3b6f-44b3-86b4-3a0c119c0438
Loading spike sorting for session  dda5fc59-f09a-4256-9fb5-66c67667a466
Loading spike sorting for session  db4df448-e449-4a6f-a0e7-288711e7a75a
Loading spike sorting for session  ecb5520d-1358-434c-95ec-93687ecd1396
Loading spike sorting for session  ee40aece-cffd-4edb-a4b6-155f158c666a
Loading spike sorting for session  b03fbc44-3d8e-4a6c-8a50-5ea3498568e0
Loading spike sorting for session  a8a8af78-16de-4841-ab07-fde4b5281a03
Loading spike sorting for session  4b7fbad4-f6de-43b4-9b15-c7c7ef44db4b
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27
Len clusters:  27

old : "2024-05-06" - 28 clusters

new 2024 : "2025-03-03" - 34 clusters

new 2022 : "2025-03-03" - 34 clusters

In [7]:
#n_folds = 1
n_folds = 100

train_data_folds, test_data_folds = dataloader.new_folds(n_folds)

__train_data_folds = []
__test_data_folds = []

ys_compare_new = []
ys_compare_t_new = []
for i in range(n_folds):
    _,ys,_,cs = train_data_folds[i]
    ys_compare_new.append(ys)
    _,ys_t,_,cs_t = test_data_folds[i]
    ys_compare_t_new.append(ys_t)

    # filter bad neurons/sessions
    min_neurons = 100
    min_trials = 20

    valid = [i for i in range(len(ys)) if ys[i].shape[2] >= min_neurons and ys[i].shape[0] >= min_trials]
    ys = [y[:,:,jnp.argsort(y.mean(0).std(0))[:100]] for y in ys]

    ys = [ys[i].mean(0) for i in valid]
    cs = [cs[i].mean(0) for i in valid]

    ys_t = [ys_t[i].mean(0) for i in valid]
    cs_t = [cs_t[i].mean(0) for i in valid]

    S = len(ys)
    __train_data_folds.append([ys,cs])
    __test_data_folds.append([ys_t,cs_t])

# # save pickle
import pickle
with open("100_folds_1_time_point.pkl","wb") as f:
    pickle.dump([params,__train_data_folds,__test_data_folds],f)

:

In [4]:
ys_compare

[(array([[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[1., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 1., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         ...,

         [[2., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [2., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 1., 0.],
          [0., 1., 0., ..., 0., 0., 0.]],

         [[0., 1., 0., ..., 0., 0., 0.],
          [1., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 2., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 1., 0., ..., 0., 0., 0.],
          [1., 1., 0., ..., 0., 0., 0.]]], shape=(18, 90, 475)),),
 (array([[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[1., 0., 1., ..., 0., 0., 0.],
          [1., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 1., ..., 0., 0., 0.]],

         [[0., 0., 1., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 2., 0., ..., 0., 0., 0.],
          [0., 2., 0., ..., 0., 0., 0.]],

         [[2., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [2., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 1., 0.],
          [0., 1., 0., ..., 0., 0., 0.]],

         [[0., 1., 0., ..., 0., 0., 0.],
          [1., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 2., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]]], shape=(18, 90, 475)),)]

In [101]:
ys_compare_new

[(array([[[0., 0., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 1., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[1., 0., 1., ..., 0., 0., 0.],
          [1., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 1., ..., 0., 0., 0.]],

         ...,

         [[0., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [1., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.]],

         [[0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 2., 0., ..., 0., 0., 0.],
          [0., 2., 0., ..., 0., 0., 0.]]], shape=(18, 90, 475)),),
 (array([[[0., 0., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 1., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         ...,

         [[1., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.]],

         [[0., 1., 0., ..., 0., 0., 0.],
          [1., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 2., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 1., 0., ..., 0., 0., 0.],
          [1., 1., 0., ..., 0., 0., 0.]]], shape=(18, 90, 475)),)]

In [27]:
hash_old = ys_compare[0][0].tolist()

In [30]:
len(hash_old[0])

90

In [60]:
ys_old[trial][t].shape

(475,)

In [ ]:
np.dtype((np.void, big_neurons.dtype.itemsize * big_neurons.shape[1]))

dtype('V720')

In [ ]:
import numpy as np

ys_old = ys_compare[0][0]
ys_new = ys_compare_new[0][0]

for t in range(ys_old.shape[0]):
    # reshape neurons as rows: (n_neurons, 90)
    big_neurons   = np.ascontiguousarray(ys_new[t].T)    # (600, 90)
    small_neurons = np.ascontiguousarray(ys_old[t].T)  # (400, 90)

    # convert to structured array for row-wise comparison
    big_view = big_neurons.view(
        np.dtype((np.void, big_neurons.dtype.itemsize * big_neurons.shape[1]))
    )
    small_view = small_neurons.view(
        np.dtype((np.void, small_neurons.dtype.itemsize * small_neurons.shape[1]))
    )

    if not np.all(np.isin(small_view, big_view)):
        print('Not in')

    break

Not in

In [ ]:
row_big = [np.array2string(row)[1:-1] for row in big_neurons]

In [78]:
row_small = [np.array2string(row)[1:-1] for row in small_neurons]

In [73]:
big_neurons[0].astype(str)

array(['1.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '1.0', '0.0', '0.0', '0.0', '1.0', '1.0', '1.0', '0.0', '1.0',
       '0.0', '0.0', '2.0', '0.0', '0.0', '1.0', '0.0', '1.0', '0.0',
       '1.0', '0.0', '0.0', '2.0', '2.0', '1.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '1.0', '1.0', '0.0', '1.0', '0.0', '0.0', '0.0',
       '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '1.0', '1.0', '0.0',
       '0.0', '1.0', '1.0', '0.0', '1.0', '1.0', '0.0', '0.0', '2.0',
       '0.0', '0.0', '0.0', '0.0', '2.0', '0.0', '0.0', '1.0', '0.0',
       '0.0', '0.0', '0.0', '1.0', '2.0', '0.0', '0.0', '1.0', '0.0',
       '1.0', '1.0', '1.0', '1.0', '0.0', '0.0', '1.0', '1.0', '1.0'],
      dtype='<U32')

In [82]:
row_big = np.array([''.join(row.astype(str)) for row in big_neurons])
row_small = np.array([''.join(row.astype(str)) for row in small_neurons])

np.isin(row_small, row_big).sum()

np.int64(248)

In [71]:
row_big

array(['1.00.01.00.00.00.00.00.00.01.00.00.00.01.01.01.00.01.00.00.02.00.00.01.00.01.00.01.00.00.02.02.01.00.00.00.00.00.01.01.00.01.00.00.00.01.00.00.00.00.00.01.01.00.00.01.01.00.01.01.00.00.02.00.00.00.00.02.00.00.01.00.00.00.00.01.02.00.00.01.00.01.01.01.01.00.00.01.01.01.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.01.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.0',
       '0.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.01.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.01.00.01.00.01.01.00.00.01.00.00.01.00.00.00.01.00.01.00.01.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.0',
       '2.02.01.01.02.01.02.01.00.01.02.01.05.03.02.01.03.01.01.01.04.01.02.02.01.01.00.01.01.01.01.02.04.02.02.02.02.02.01.00.02.03.01.03.02.02.00.03.01.02.01.03.03.01.01.03.00.03.05.04.03.02.02.01.01.00.01.00.00.02.04.02.01.01.01.01.03.01.00.01.01.02.03.01.00.01.02.00.01.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '3.01.01.01.00.00.03.00.03.01.01.01.03.00.01.00.01.00.03.03.02.02.02.01.01.01.00.00.02.00.04.00.01.00.04.03.03.03.01.01.02.02.03.01.01.03.03.02.01.02.02.04.00.01.01.00.01.01.02.01.02.01.05.00.03.03.01.01.01.01.02.01.01.02.02.03.01.01.01.00.02.03.01.02.01.02.01.01.02.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.03.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.01.01.01.00.00.00.00.00.00.01.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.01.01.02.01.00.00.01.01.02.00.00.00.00.01.00.02.01.01.00.00.00.01.00.00.00.00.00.00.01.02.01.01.00.00.01.01.01.00.01.01.00.00.00.01.00.00.01.00.02.00.00.00.00.02.01.02.01.00.01.00.00.01.00.00.00.00.00.01.00.00.00.01.00.00.00.01.01.01.00.00.00.00.00.00.01.02.00.00.00.0',
       '0.00.00.01.01.01.00.01.00.01.00.01.01.00.00.00.00.00.00.00.04.01.00.00.00.00.01.01.00.02.00.00.01.00.01.00.00.00.00.00.00.00.00.00.01.01.01.01.01.02.01.00.00.00.01.00.01.00.01.03.01.00.01.00.01.02.02.01.01.01.00.02.00.01.02.03.04.02.00.00.01.00.00.02.00.00.01.00.01.00.0',
       '0.00.00.01.00.00.00.00.00.01.01.00.00.00.00.00.00.00.00.01.00.01.00.00.00.00.00.00.01.00.01.03.00.00.00.01.00.00.00.00.01.01.00.01.00.00.01.00.00.01.00.02.02.02.06.02.00.00.02.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '1.01.01.03.02.03.02.03.02.03.03.01.01.03.02.02.01.01.03.01.01.00.01.03.06.00.03.03.01.01.01.01.01.01.02.02.01.02.01.01.01.02.02.02.01.00.05.00.02.04.01.01.03.03.02.07.05.01.03.03.02.00.02.02.01.01.02.02.04.04.03.03.02.03.03.03.01.02.01.03.03.00.02.04.02.03.02.00.02.04.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.01.00.01.00.01.00.00.00.01.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.01.01.00.00.01.01.01.01.00.01.00.01.01.00.01.03.00.02.01.03.00.00.01.01.00.00.00.00.00.00.00.00.02.01.00.0',
       '1.00.01.00.01.01.01.00.00.01.00.00.00.01.00.01.00.00.01.00.00.00.00.00.01.00.01.00.00.00.00.00.00.00.00.00.01.01.00.00.00.00.01.01.01.00.01.01.01.00.00.00.00.00.00.00.00.01.00.00.00.00.01.00.00.00.00.00.00.00.00.00.01.00.00.01.00.00.01.00.01.00.01.00.01.00.00.01.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.01.00.01.00.00.00.00.00.00.01.01.00.00.00.00.00.01.02.02.00.00.00.01.00.01.00.02.02.00.00.01.01.00.01.00.01.00.00.00.02.02.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.01.01.00.0',
       '1.00.00.00.00.00.00.00.01.00.00.01.00.00.01.01.00.01.00.00.01.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.01.00.01.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.01.00.00.00.00.00.01.00.00.00.01.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.01.00.01.00.01.00.01.00.00.00.00.01.00.00.01.00.00.00.00.00.00.01.00.00.00.00.01.00.00.00.00.00.00.00.00.00.02.01.00.00.00.00.00.00.0',
       '1.01.00.00.01.00.00.00.00.00.01.02.04.03.01.00.02.01.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.01.01.00.00.01.00.02.01.00.00.00.00.00.02.02.00.00.01.01.01.01.01.01.01.00.00.01.00.01.00.01.01.00.01.01.04.02.00.00.01.00.02.01.00.01.01.00.00.00.01.02.00.02.04.02.02.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.01.00.00.00.00.00.00.01.00.00.00.00.00.00.01.01.02.01.00.02.00.00.00.00.01.01.01.01.00.01.00.00.00.00.01.00.01.00.00.01.01.01.01.00.00.01.02.03.01.02.01.00.00.00.00.01.02.00.00.00.00.00.00.00.00.00.00.01.00.01.01.01.00.0',
       '0.00.01.00.00.00.00.00.00.01.00.00.00.00.00.01.00.00.00.00.00.01.00.01.00.00.00.00.01.00.00.00.00.01.00.00.00.00.00.00.00.00.00.02.02.00.00.00.00.00.00.01.00.02.03.02.02.03.02.01.00.02.00.00.00.01.01.02.01.01.00.00.02.01.01.00.00.00.00.02.01.02.02.00.00.00.00.01.00.00.0',
       '0.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.01.00.01.01.01.00.00.00.00.00.00.00.01.01.00.00.01.00.01.01.00.01.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.01.00.01.01.01.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.01.00.01.00.00.01.00.00.01.00.01.00.00.00.00.00.00.00.00.00.00.01.01.00.00.01.01.00.01.01.00.00.03.00.00.00.00.01.00.01.00.0',
       '0.00.00.01.01.00.00.00.00.00.01.00.00.00.01.00.00.00.00.01.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.02.01.00.01.00.00.01.01.00.01.01.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.01.00.00.00.00.02.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.01.01.00.02.00.00.00.00.00.00.00.01.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.02.00.00.00.00.01.00.00.00.0',
       '0.00.00.00.00.00.00.00.01.01.00.00.01.00.00.00.00.00.01.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.01.00.00.00.01.00.00.00.00.00.01.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.02.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.02.00.00.00.00.00.00.01.00.00.00.00.00.01.00.00.00.00.00.00.01.00.00.00.01.00.01.00.00.00.00.00.00.00.00.00.00.02.01.00.00.00.00.00.00.01.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.01.00.00.01.0',
       '0.00.00.00.00.00.00.00.01.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.01.00.00.00.00.00.00.00.00.00.01.00.05.00.00.00.00.00.00.0',
       '1.01.01.00.01.00.00.01.00.00.00.01.01.03.03.02.00.00.02.00.01.01.01.00.01.00.01.00.02.01.00.01.00.01.01.00.00.01.02.02.00.00.01.00.03.01.00.03.00.03.00.01.00.02.00.01.01.00.03.01.00.02.00.00.00.00.00.03.02.00.01.00.00.00.04.03.00.02.02.01.01.01.01.00.01.02.02.01.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.01.01.01.00.00.00.00.00.00.00.00.01.01.00.00.01.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.0',
       '0.01.00.00.00.01.00.00.00.00.00.01.00.01.00.01.01.00.01.00.00.00.01.01.00.00.00.00.01.00.01.00.00.00.00.00.00.00.01.00.04.00.02.02.01.02.00.01.01.01.01.02.00.00.00.01.02.01.01.00.00.00.00.00.00.00.00.00.00.01.01.00.01.01.00.01.01.00.00.01.01.00.01.00.00.00.00.00.00.00.0',
       '1.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.04.04.01.00.01.01.00.02.01.02.03.03.00.00.00.00.00.02.00.00.02.07.00.00.00.00.00.00.00.00.02.01.00.01.00.01.04.00.02.00.00.00.00.00.00.00.00.00.00.00.01.04.01.00.00.00.00.00.00.02.05.05.00.00.01.00.04.07.03.01.03.04.0',
       '0.01.00.00.00.01.00.00.00.00.00.00.00.00.00.01.01.00.00.00.00.01.00.00.00.00.00.00.00.00.03.00.00.00.00.01.01.02.00.01.00.00.00.00.00.00.00.00.00.02.00.02.00.00.00.00.00.00.01.01.00.01.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.01.00.00.01.01.00.00.0',
       '0.00.00.00.01.00.00.00.00.01.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.01.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.01.00.00.00.02.01.00.00.00.00.00.00.00.00.00.02.00.00.00.00.00.00.01.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.01.00.00.00.01.00.01.00.01.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.01.00.01.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.01.00.00.00.00.00.00.01.01.02.02.02.01.00.00.00.00.00.01.00.00.01.01.00.00.00.01.00.00.01.00.00.01.00.00.00.00.00.00.01.02.02.00.00.00.01.01.00.00.00.00.00.01.00.00.01.00.01.00.01.01.02.00.01.00.00.00.00.00.01.01.00.00.00.02.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.01.00.00.00.00.00.01.01.00.01.00.00.00.00.01.02.03.01.02.05.02.00.00.01.00.00.01.01.00.01.03.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '1.01.03.01.03.01.01.02.01.03.00.02.01.00.01.02.02.02.00.02.03.01.01.02.02.01.01.02.01.02.02.02.02.04.00.00.01.03.02.01.02.02.03.02.00.02.01.01.02.01.02.01.03.00.02.01.01.02.02.00.01.01.01.01.01.01.01.01.02.01.02.03.03.02.01.02.02.03.03.00.03.02.01.02.01.01.01.02.02.00.0',
       '1.01.01.01.01.00.00.01.00.00.00.01.00.00.01.00.01.01.00.00.00.00.01.01.00.00.00.00.00.00.01.03.00.01.00.02.01.01.01.00.01.01.02.01.01.00.00.01.00.00.00.01.00.01.03.01.00.00.01.02.00.01.01.00.00.00.00.00.00.00.01.00.01.01.00.00.00.02.00.01.00.00.01.00.00.00.01.00.01.00.0',
       '0.00.00.00.00.00.00.00.01.00.00.00.01.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.01.00.00.00.01.00.00.01.00.01.01.00.01.00.01.00.01.01.00.01.01.00.00.00.00.00.01.00.01.00.00.00.01.00.02.01.00.00.01.00.00.00.00.01.00.00.00.00.00.00.00.00.0',
       '0.00.00.01.00.00.00.02.00.01.00.00.00.01.00.00.00.00.00.00.00.00.00.00.01.01.01.00.00.01.00.00.01.00.00.00.00.00.00.00.00.01.00.00.00.00.01.01.01.00.01.01.00.00.00.01.00.01.00.00.00.00.00.00.01.01.01.01.00.00.00.01.00.01.00.00.00.00.00.00.00.00.04.00.00.01.00.01.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.01.00.02.03.00.02.02.01.02.00.00.00.01.01.00.00.01.01.00.00.00.02.00.01.00.00.00.01.02.00.01.00.01.01.01.02.01.02.01.00.01.02.01.01.02.01.01.02.02.01.02.03.00.00.01.01.00.00.01.02.01.00.00.00.00.00.01.00.02.02.03.00.01.01.02.01.00.01.00.01.01.00.00.00.00.00.01.00.01.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '1.00.00.01.02.00.00.00.01.01.00.00.01.00.01.02.01.01.00.00.00.00.00.01.00.00.01.01.01.00.00.00.00.00.01.00.00.00.04.00.00.00.01.02.00.02.00.01.02.00.00.01.01.00.01.00.01.01.00.00.01.01.00.00.00.01.01.00.01.00.01.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.02.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.03.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.03.01.03.01.01.02.00.00.00.00.00.00.01.01.03.00.02.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.01.00.00.00.00.01.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.01.00.00.01.00.00.01.02.00.00.00.00.00.00.02.00.00.00.00.00.00.00.01.00.00.02.00.00.00.00.00.01.01.01.00.02.00.00.00.01.00.04.00.01.00.05.01.03.00.00.01.00.01.02.00.00.00.00.01.00.01.01.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.03.01.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.01.00.00.01.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.0',
       '0.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.01.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.01.00.00.00.00.00.00.00.01.02.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.02.00.00.00.01.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.03.00.00.00.00.00.00.00.0',
       '0.01.00.00.01.00.00.00.01.00.00.00.01.00.01.00.00.01.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.01.00.00.00.00.04.01.00.00.00.00.01.00.00.03.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.01.01.00.01.00.00.01.01.00.01.00.04.04.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.01.02.01.00.02.00.00.00.00.00.00.00.03.04.02.02.00.00.00.00.00.00.02.00.00.01.02.00.02.01.00.02.02.01.02.01.00.00.01.01.00.00.00.00.00.02.00.01.02.01.00.02.00.01.03.02.01.02.01.00.00.00.00.02.00.00.00.01.00.00.00.01.00.00.00.00.00.00.00.01.01.00.00.01.01.02.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.05.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.01.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.02.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.01.01.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.0',
       '0.01.00.00.00.00.00.00.01.00.00.00.00.01.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.01.00.01.00.01.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.05.00.01.01.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',
       '1.01.00.00.00.00.00.00.00.00.05.00.00.00.00.01.00.00.00.00.03.00.00.00.00.00.00.00.00.02.00.01.00.00.00.01.00.01.00.00.00.00.01.02.00.00.01.00.01.01.04.02.00.00.00.01.00.00.00.00.00.00.01.02.00.00.00.00.00.00.01.00.00.00.00.00.01.00.00.01.00.00.00.00.01.00.01.01.00.00.0',
       '1.00.01.00.00.01.01.01.00.01.01.01.00.00.00.00.02.01.00.00.00.01.00.00.01.00.01.01.01.02.00.00.00.00.00.00.00.00.00.00.01.01.01.01.01.00.00.00.02.01.00.00.00.00.00.00.01.01.01.00.01.01.01.00.01.00.00.00.00.00.00.01.00.00.00.01.00.00.00.00.00.00.00.01.00.00.00.00.00.01.0',
       '0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0',

In [ ]:
small_neurons[4] in

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [64]:
(np.isin(small_view, big_view))

array([[False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [62]:
small_neurons[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       2., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 1., 0., 0.])

In [61]:
small_view[0]

array([b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
      dtype='|V720')

In [48]:
big_view

array([[b'\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F'],
       [b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
       [b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
       [b'\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x14\x40\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x10\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x10\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\x14\x40\x00\x00\x00\x00\x00\x00\x10\x40\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x10\x40\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00'],
       [b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
       [b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],

In [5]:
ys_compare

[(array([[[0., 0., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 1., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 2., 0., ..., 0., 0., 0.],
          [0., 2., 0., ..., 0., 0., 0.]],

         [[2., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [2., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 1., 0.],
          [0., 1., 0., ..., 0., 0., 0.]],

         [[0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 1., 0., ..., 0., 0., 0.],
          [1., 1., 0., ..., 0., 0., 0.]]], shape=(18, 90, 475)),
  array([[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]]], shape=(21, 90, 237)),
  array([[[2., 1., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 3., 0., ..., 0., 0., 0.],
          [0., 0., 2., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.]],

         [[1., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [4., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [2., 1., 0., ..., 0., 0., 0.]],

         ...,

         [[0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [3., 0., 0., ..., 0., 0., 0.]],

         [[3., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 2., 0., ..., 0., 0., 0.]],

         [[2., 0., 0., ..., 0., 0., 0.],
          [2., 0., 0., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 1.],
          [3., 1., 0., ..., 0., 0., 0.]]], shape=(33, 90, 243)),
  array([[[0., 0., 3., ..., 0., 0., 0.],
          [0., 1., 3., ..., 0., 0., 0.],
          [0., 0., 4., ..., 0., 0., 0.],
          ...,
          [0., 0., 1., ..., 0., 0., 0.],
          [1., 1., 3., ..., 0., 0., 0.],
          [0., 0., 4., ..., 0., 0., 0.]],

         [[0., 0., 3., ..., 0., 0., 0.],
          [1., 0., 4., ..., 0., 0., 0.],
          [0., 1., 2., ..., 0., 0., 0.],
          ...,
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 1., 3., ..., 0., 0., 0.],
          [1., 4., 3., ..., 0., 0., 0.],
          [1., 0., 3., ..., 0., 0., 0.],
          ...,
          [0., 2., 3., ..., 0., 0., 0.],
          [0., 1., 3., ..., 0., 0., 0.],
          [0., 1., 2., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 5., ..., 0., 0., 0.],
          [0., 0., 5., ..., 0., 0., 0.],
          [0., 0., 5., ..., 0., 0., 0.],
          ...,
          [0., 0., 3., ..., 0., 0., 0.],
          [0., 0., 3., ..., 0., 0., 0.],
          [0., 2., 3., ..., 0., 0., 0.]],

         [[0., 0., 7., ..., 0., 0., 0.],
          [1., 1., 5., ..., 0., 0., 0.],
          [0., 0., 3., ..., 0., 0., 0.],
          ...,
          [0., 0., 5., ..., 0., 0., 0.],
          [0., 0., 5., ..., 0., 0., 0.],
          [0., 0., 4., ..., 0., 0., 0.]],

         [[0., 0., 4., ..., 0., 0., 0.],
          [2., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 2., 0., ..., 0., 0., 0.]]], shape=(21, 90, 311)),
  array([[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 1., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [2., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]]], shape=(25, 90, 356)),
  array([[[1., 0., 0., ..., 0., 0., 0.],
          [3., 0., 3., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 0., 0.],
          ...,
          [2., 0., 0., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[1., 0., 0., ..., 0., 0., 0.],
          [1., 0., 8., ..., 0., 0., 0.],
          [2., 0., 4., ..., 0., 0., 0.],
          ...,
          [2., 0., 1., ..., 0., 0., 0.],
          [1., 0., 2., ..., 0., 0., 0.],
          [0., 0., 2., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 4., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 1., ..., 0., 0., 0.],
          [2., 0., 1., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 0., ..., 0., 0., 0.],
          [2., 1., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [3., 0., 0., ..., 0., 0., 0.],
          [3., 0., 0., ..., 1., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [2., 0., 1., ..., 0., 0., 0.],
          [1., 1., 1., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [4., 0., 0., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 0., 0.]],

         [[0., 1., 0., ..., 0., 0., 0.],
          [1., 0., 7., ..., 0., 0., 0.],
          [2., 0., 6., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [2., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.]]], shape=(16, 90, 470)),
  array([[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]]], shape=(14, 90, 351)),
  array([[[0., 1., 2., ..., 0., 0., 0.],
          [0., 1., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 1., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 4., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          ...,
          [0., 0., 3., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 3., ..., 0., 0., 0.]],

         [[0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 7., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          ...,
          [0., 0., 3., ..., 0., 0., 0.],
          [0., 0., 3., ..., 0., 0., 0.],
          [0., 0., 2., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 2., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 3., ..., 0., 0., 0.],
          ...,
          [0., 0., 4., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 4., ..., 0., 0., 0.]],

         [[0., 0., 3., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 2., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.]]], shape=(14, 90, 354)),
  array([[[0., 1., 1., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 2., ..., 0., 0., 0.],
          [0., 2., 1., ..., 0., 0., 0.],
          [0., 1., 1., ..., 0., 0., 0.]],

         [[0., 1., 1., ..., 0., 0., 0.],
          [0., 3., 0., ..., 0., 0., 0.],
          [0., 1., 1., ..., 0., 0., 0.],
          ...,
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 4., 0., ..., 0., 0., 0.]],

         [[0., 0., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 2., 1., ..., 0., 0., 0.],
          [0., 2., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 2., 0., ..., 0., 0., 0.],
          [0., 1., 1., ..., 0., 0., 0.],
          [0., 1., 2., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 1., 2., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          ...,
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 2., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.]]], shape=(26, 90, 460)),
  array([[[1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [2., 1., 0., ..., 0., 0., 0.],
          ...,
          [3., 3., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[2., 0., 0., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 0., 0.],
          ...,
          [1., 1., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 1., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.]],

         [[0., 2., 1., ..., 0., 1., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 1., 0., ..., 0., 0., 0.],
          ...,
          [0., 2., 0., ..., 0., 0., 0.],
          [2., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 1., 1., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          ...,
          [1., 0., 1., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 0., 0.]]], shape=(17, 90, 406)),
  array([[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 1., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 2., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          ...,
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 2., ..., 0., 0., 0.]]], shape=(30, 90, 453)),
  array([[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          ...,
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         ...,

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [1., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [1., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]]], shape=(14, 90, 379)),
  array([[[0., 0., 1., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 1., ..., 0., 0., 0.],

In [ ]:
xs,ys,rs,cs = dataloader.load_train_data()

valid_cs = np.array([cs[i] for i in valid],dtype=object)

import pickle
with open("raw_behavior.pkl","wb") as f:
    pickle.dump(cs,f)